db:
  host: 'localhost'
  port: 3306
  user: 'root'
  password: 'Kolian18**'
  name: 'choice'
  limit: 50

cache:
  address: '192.168.178.17'
  port: ':6379'
  password: 'Awesome85**'
  db: 0
  pool_size: 25
  minimum_idle_connections: 10
  maximum_retries: 1