db:
  host: '192.168.0.64'
  port: 3306
  user: 'dev'
  password: 'Awesome85**'
  name: 'choice'
  limit: 50

cache:
  address: '192.168.0.64'
  port: ':6379'
  password: 'Awesome85**'
  db: 0
  pool_size: 25
  minimum_idle_connections: 10
  maximum_retries: 1